---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: betamax
  name: betamax

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: duckdns
  name: duckdns

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: traefik
  name: traefik

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: metallb
  name: metallb-system

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: monocle
  name: monocle

#---
#apiVersion: v1
#kind: Namespace
#metadata:
  #labels:
    #name: kafka
  #annotations:
    #fluxcd.io/ignore: true
  #name: kafka

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: chaos
  name: chaos

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: heimdall
  name: heimdall

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: db
  annotations:
    fluxcd.io/ignore: true
  name: db

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: pihole
  annotations:
    fluxcd.io/ignore: true
  name: pihole
