---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: betamax
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          ports:
          - name: web
            containerPort: 8989
          volumeMounts:
          - name: config
            mountPath: "/config"
          - name: tvseries
            mountPath: "/tvseries"
          - name: downloads
            mountPath: "/downloads"
          env:
            - name: TZ
              value: Europe/Copenhagen
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: tvseries
        persistentVolumeClaim:
          claimName: plex-tvseries
      - name: downloads
        persistentVolumeClaim:
          claimName: transmission-downloads

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: betamax
spec:
  type: ClusterIP
  selector:
    app: sonarr
  ports:
  - name: web
    protocol: TCP
    port: 8989
    targetPort: web

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: betamax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


