---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: betamax
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          ports:
          - name: web
            containerPort: 7878
          volumeMounts:
          - name: config
            mountPath: "/config"
          - name: movies
            mountPath: "/movies"
          - name: downloads
            mountPath: "/downloads"
          env:
            - name: TZ
              value: Europe/Copenhagen
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: movies
        persistentVolumeClaim:
          claimName: plex-movies
      - name: downloads
        persistentVolumeClaim:
          claimName: transmission-downloads

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: betamax
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
  - name: web
    protocol: TCP
    port: 7878
    targetPort: web

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: betamax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

