---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcarlsen-webapp
  namespace: webapp
  labels:
    app: wcarlsen-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcarlsen-webapp
  template:
    metadata:
      labels:
        app: wcarlsen-webapp
    spec:
      containers:
      - name: wcarlsen-webapp
        image: wcarlsen/wcarlsen-webapp:1.0
        ports:
        - name: web
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: wcarlsen-webapp
  namespace: webapp
spec:
  type: ClusterIP
  selector:
    app: wcarlsen-webapp
  ports:
  - name: web
    protocol: TCP
    port: 3000
    targetPort: 3000


